/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.squidy.nodes.directinputmouse;

public class CDirectInputMouse {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CDirectInputMouse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CDirectInputMouse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DirectInputMouseJNI.delete_CDirectInputMouse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CDirectInputMouse() {
    this(DirectInputMouseJNI.new_CDirectInputMouse(), true);
  }

  public int Init(int hWnd) {
    return DirectInputMouseJNI.CDirectInputMouse_Init(swigCPtr, this, hWnd);
  }

  public int StartCapture() {
    return DirectInputMouseJNI.CDirectInputMouse_StartCapture(swigCPtr, this);
  }

  public int StopCapture() {
    return DirectInputMouseJNI.CDirectInputMouse_StopCapture(swigCPtr, this);
  }

  public void WaitForBufferedData() {
    DirectInputMouseJNI.CDirectInputMouse_WaitForBufferedData(swigCPtr, this);
  }

  public void ReadBufferedData() {
    DirectInputMouseJNI.CDirectInputMouse_ReadBufferedData(swigCPtr, this);
  }

  public int GetDataCount() {
    return DirectInputMouseJNI.CDirectInputMouse_GetDataCount(swigCPtr, this);
  }

  public CDirectInputMouse.EventID GetDataEvent(int iIndex) {
    return CDirectInputMouse.EventID.swigToEnum(DirectInputMouseJNI.CDirectInputMouse_GetDataEvent(swigCPtr, this, iIndex));
  }

  public int GetDataValue(int iIndex) {
    return DirectInputMouseJNI.CDirectInputMouse_GetDataValue(swigCPtr, this, iIndex);
  }

  public int SetAxisMergeXY(boolean bAxisMergeXY) {
    return DirectInputMouseJNI.CDirectInputMouse_SetAxisMergeXY(swigCPtr, this, bAxisMergeXY);
  }

  public final static class EventID {
    public final static EventID DIMEID_UNKNOWN = new EventID("DIMEID_UNKNOWN", DirectInputMouseJNI.CDirectInputMouse_DIMEID_UNKNOWN_get());
    public final static EventID DIMEID_X = new EventID("DIMEID_X", DirectInputMouseJNI.CDirectInputMouse_DIMEID_X_get());
    public final static EventID DIMEID_Y = new EventID("DIMEID_Y", DirectInputMouseJNI.CDirectInputMouse_DIMEID_Y_get());
    public final static EventID DIMEID_XY = new EventID("DIMEID_XY", DirectInputMouseJNI.CDirectInputMouse_DIMEID_XY_get());
    public final static EventID DIMEID_Z = new EventID("DIMEID_Z", DirectInputMouseJNI.CDirectInputMouse_DIMEID_Z_get());
    public final static EventID DIMEID_BUTTON0 = new EventID("DIMEID_BUTTON0", DirectInputMouseJNI.CDirectInputMouse_DIMEID_BUTTON0_get());
    public final static EventID DIMEID_BUTTON1 = new EventID("DIMEID_BUTTON1", DirectInputMouseJNI.CDirectInputMouse_DIMEID_BUTTON1_get());
    public final static EventID DIMEID_BUTTON2 = new EventID("DIMEID_BUTTON2", DirectInputMouseJNI.CDirectInputMouse_DIMEID_BUTTON2_get());
    public final static EventID DIMEID_BUTTON3 = new EventID("DIMEID_BUTTON3", DirectInputMouseJNI.CDirectInputMouse_DIMEID_BUTTON3_get());
    public final static EventID DIMEID_BUTTON4 = new EventID("DIMEID_BUTTON4", DirectInputMouseJNI.CDirectInputMouse_DIMEID_BUTTON4_get());
    public final static EventID DIMEID_BUTTON5 = new EventID("DIMEID_BUTTON5", DirectInputMouseJNI.CDirectInputMouse_DIMEID_BUTTON5_get());
    public final static EventID DIMEID_BUTTON6 = new EventID("DIMEID_BUTTON6", DirectInputMouseJNI.CDirectInputMouse_DIMEID_BUTTON6_get());
    public final static EventID DIMEID_BUTTON7 = new EventID("DIMEID_BUTTON7", DirectInputMouseJNI.CDirectInputMouse_DIMEID_BUTTON7_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static EventID swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + EventID.class + " with value " + swigValue);
    }

    private EventID(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private EventID(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private EventID(String swigName, EventID swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static EventID[] swigValues = { DIMEID_UNKNOWN, DIMEID_X, DIMEID_Y, DIMEID_XY, DIMEID_Z, DIMEID_BUTTON0, DIMEID_BUTTON1, DIMEID_BUTTON2, DIMEID_BUTTON3, DIMEID_BUTTON4, DIMEID_BUTTON5, DIMEID_BUTTON6, DIMEID_BUTTON7 };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
