/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.squidy.nodes.directinputmouse;

class DirectInputMouseJNI {
  public final static native int CDirectInputMouse_DIMEID_UNKNOWN_get();
  public final static native int CDirectInputMouse_DIMEID_X_get();
  public final static native int CDirectInputMouse_DIMEID_Y_get();
  public final static native int CDirectInputMouse_DIMEID_XY_get();
  public final static native int CDirectInputMouse_DIMEID_Z_get();
  public final static native int CDirectInputMouse_DIMEID_BUTTON0_get();
  public final static native int CDirectInputMouse_DIMEID_BUTTON1_get();
  public final static native int CDirectInputMouse_DIMEID_BUTTON2_get();
  public final static native int CDirectInputMouse_DIMEID_BUTTON3_get();
  public final static native int CDirectInputMouse_DIMEID_BUTTON4_get();
  public final static native int CDirectInputMouse_DIMEID_BUTTON5_get();
  public final static native int CDirectInputMouse_DIMEID_BUTTON6_get();
  public final static native int CDirectInputMouse_DIMEID_BUTTON7_get();
  public final static native long new_CDirectInputMouse();
  public final static native void delete_CDirectInputMouse(long jarg1);
  public final static native int CDirectInputMouse_Init(long jarg1, CDirectInputMouse jarg1_, int jarg2);
  public final static native int CDirectInputMouse_StartCapture(long jarg1, CDirectInputMouse jarg1_);
  public final static native int CDirectInputMouse_StopCapture(long jarg1, CDirectInputMouse jarg1_);
  public final static native void CDirectInputMouse_WaitForBufferedData(long jarg1, CDirectInputMouse jarg1_);
  public final static native void CDirectInputMouse_ReadBufferedData(long jarg1, CDirectInputMouse jarg1_);
  public final static native int CDirectInputMouse_GetDataCount(long jarg1, CDirectInputMouse jarg1_);
  public final static native int CDirectInputMouse_GetDataEvent(long jarg1, CDirectInputMouse jarg1_, int jarg2);
  public final static native int CDirectInputMouse_GetDataValue(long jarg1, CDirectInputMouse jarg1_, int jarg2);
  public final static native int CDirectInputMouse_SetAxisMergeXY(long jarg1, CDirectInputMouse jarg1_, boolean jarg2);

  static {
    try {
      System.loadLibrary("ext/DirectInputMouse");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library 'DirectInputMouse.dll' failed to load.\n" + e);
    }
  }

}
