/**
 * Squidy Interaction Library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 * 
 * Squidy Interaction Library is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with Squidy Interaction Library. If not, see
 * <http://www.gnu.org/licenses/>.
 * 
 * 2009 Human-Computer Interaction Group, University of Konstanz.
 * <http://hci.uni-konstanz.de>
 * 
 * Please contact info@squidy-lib.de or visit our website
 * <http://www.squidy-lib.de> for further information.
 */




//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.10 at 04:17:09 PM CEST 
//


package org.squidy.nodes.tracking.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for camera complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="camera">
 *   &lt;complexContent>
 *     &lt;extension base="{}propertyContainer">
 *       &lt;sequence>
 *         &lt;element name="corners" type="{}corners" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="online" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="tracking" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "camera", propOrder = {
    "corners"
})
public class Camera
    extends PropertyContainer
{

    @Override
	public String toString() {
		return "cam" + getId() + " (online=" + isOnline() + ", msg=\"" + getMsg() + "\"): " + super.toString();
	}

	protected Corners corners;
    @XmlAttribute
    protected Boolean online;
    @XmlAttribute
    protected Boolean tracking;

    /**
     * @author Jo Bieg
     */
    public Camera() {
		super();
		// TODO Auto-generated constructor stub
	}

    /**
     * @author Jo Bieg
     * @param id
     */
	public Camera(String id) {
		super();
		this.id = id;
	}
	
    /**
     * Gets the value of the corners property.
     * 
     * @return
     *     possible object is
     *     {@link Corners }
     *     
     */
    public Corners getCorners() {
        return corners;
    }

    /**
     * Sets the value of the corners property.
     * 
     * @param value
     *     allowed object is
     *     {@link Corners }
     *     
     */
    public void setCorners(Corners value) {
        this.corners = value;
    }

    /**
     * Gets the value of the online property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnline() {
        return online;
    }

    /**
     * Sets the value of the online property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnline(Boolean value) {
        this.online = value;
    }

    /**
     * Gets the value of the tracking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTracking() {
        return tracking;
    }

    /**
     * Sets the value of the tracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTracking(Boolean value) {
        this.tracking = value;
    }

}
